/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils */

#ifndef _Included_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils
#define _Included_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif

#include <android/log.h>
#include <string.h>
#include <jni.h>

#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG  , "JNIDEBUG", __VA_ARGS__)

#define celToFar(cel) (cel * 9 / 5 + 32)
#define farToCel(far) ((far - 32) * 5 / 9)

JNIEXPORT jstring JNICALL Java_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

JNIEXPORT jfloat JNICALL Java_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils_celToFar
  (JNIEnv *, jobject, jfloat);

JNIEXPORT jfloat JNICALL Java_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils_farToCel
        (JNIEnv *env, jobject, jfloat);

JNIEXPORT jobject JNICALL Java_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils_convertDayListToFar
  (JNIEnv *, jobject, jobject);

JNIEXPORT jobject JNICALL Java_nyu_cs_jessicahuang_temperaturec_Controller_NdkJniUtils_convertDayListToCel
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
